package com.jlcindia.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CourseManagerService service = new CourseManagerService();
 * CourseManagerDelegate portType = service.getCourseManagerPort();
 * portType.getAllCourses(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CourseManagerService", targetNamespace = "http://jaxws.jlcindia.com/", wsdlLocation = "http://localhost:1234/Lab5/CourseManagerPort?wsdl")
public class CourseManagerService extends Service {

	private final static URL COURSEMANAGERSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.jlcindia.jaxws.client.CourseManagerService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.jlcindia.jaxws.client.CourseManagerService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:1234/Lab5/CourseManagerPort?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://localhost:1234/Lab5/CourseManagerPort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		COURSEMANAGERSERVICE_WSDL_LOCATION = url;
	}

	public CourseManagerService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CourseManagerService() {
		super(COURSEMANAGERSERVICE_WSDL_LOCATION, new QName(
				"http://jaxws.jlcindia.com/", "CourseManagerService"));
	}

	/**
	 * 
	 * @return returns CourseManagerDelegate
	 */
	@WebEndpoint(name = "CourseManagerPort")
	public CourseManagerDelegate getCourseManagerPort() {
		return super.getPort(new QName("http://jaxws.jlcindia.com/",
				"CourseManagerPort"), CourseManagerDelegate.class);
	}

}
