package com.jlcindia.jaxws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CourseManagerDelegate", targetNamespace = "http://jaxws.jlcindia.com/")
public interface CourseManagerDelegate {

	/**
	 * 
	 * @return returns java.util.List<com.jlcindia.jaxws.client.CourseTO>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getAllCourses", targetNamespace = "http://jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.client.GetAllCourses")
	@ResponseWrapper(localName = "getAllCoursesResponse", targetNamespace = "http://jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.client.GetAllCoursesResponse")
	public List<CourseTO> getAllCourses();

}
