package com.jlcindia.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 14:31:02 IST 2012
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://cxf.jlcindia.com/", name = "StudentService")
@XmlSeeAlso({ObjectFactory.class})
public interface StudentService {

    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://cxf.jlcindia.com/", className = "com.jlcindia.cxf.GetStudentResponse")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://cxf.jlcindia.com/", className = "com.jlcindia.cxf.GetStudent")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod(action = "urn:GetStudent")
    public com.jlcindia.cxf.Student getStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @ResponseWrapper(localName = "addStudentResponse", targetNamespace = "http://cxf.jlcindia.com/", className = "com.jlcindia.cxf.AddStudentResponse")
    @RequestWrapper(localName = "addStudent", targetNamespace = "http://cxf.jlcindia.com/", className = "com.jlcindia.cxf.AddStudent")
    @WebMethod(action = "urn:AddStudent")
    public void addStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.jlcindia.cxf.Student arg0
    );
}
