
package com.jlcindia.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 14:31:02 IST 2012
 * Generated source version: 2.2.12
 * 
 */

public final class StudentService_StudentServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.jlcindia.com/", "StudentServiceService");

    private StudentService_StudentServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = StudentServiceService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StudentServiceService ss = new StudentServiceService(wsdlURL, SERVICE_NAME);
        StudentService port = ss.getStudentServicePort();  
        
        {
        System.out.println("Invoking getStudent...");
        java.lang.String _getStudent_arg0 = "_getStudent_arg0-980203854";
        com.jlcindia.cxf.Student _getStudent__return = port.getStudent(_getStudent_arg0);
        System.out.println("getStudent.result=" + _getStudent__return);


        }
        {
        System.out.println("Invoking addStudent...");
        com.jlcindia.cxf.Student _addStudent_arg0 = new com.jlcindia.cxf.Student();
        _addStudent_arg0.setEmail("Email-276464367");
        _addStudent_arg0.setFname("Fname-1226132816");
        _addStudent_arg0.setLname("Lname818681056");
        _addStudent_arg0.setSid("Sid232079380");
        port.addStudent(_addStudent_arg0);


        }

        System.exit(0);
    }

}
