
package com.jlcindia.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 14:29:02 IST 2012
 * Generated source version: 2.2.12
 */

@XmlRootElement(name = "addStudent", namespace = "http://cxf.jlcindia.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addStudent", namespace = "http://cxf.jlcindia.com/")

public class AddStudent {

    @XmlElement(name = "arg0")
    private com.jlcindia.cxf.Student arg0;

    public com.jlcindia.cxf.Student getArg0() {
        return this.arg0;
    }

    public void setArg0(com.jlcindia.cxf.Student newArg0)  {
        this.arg0 = newArg0;
    }

}

