
package com.jlcindia.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 14:29:02 IST 2012
 * Generated source version: 2.2.12
 */

@XmlRootElement(name = "getStudentResponse", namespace = "http://cxf.jlcindia.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getStudentResponse", namespace = "http://cxf.jlcindia.com/")

public class GetStudentResponse {

    @XmlElement(name = "return")
    private com.jlcindia.cxf.Student _return;

    public com.jlcindia.cxf.Student getReturn() {
        return this._return;
    }

    public void setReturn(com.jlcindia.cxf.Student new_return)  {
        this._return = new_return;
    }

}

