package com.jlcindia.jaxws.sms.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SendSMSHttpPost", targetNamespace = "http://www.webserviceX.NET")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SendSMSHttpPost {

	/**
	 * Send unlimited free SMS to India - Maximum message size is 120 characters<br>
	 * <br>
	 * <b>Usage:</b>If your mobile number is 098XXXXXXXX ,Please enter as
	 * 98XXXXXXXX<br>
	 * <b>Network Covered:</b> Airtel,Idea Cellular,Skycell ,RPG
	 * Cellular,Hutch,Celforce / Fascel,BPL Mobile,Escotel
	 * 
	 * @param mobileNumber
	 * @param fromEmailAddress
	 * @param message
	 * @return returns com.jlcindia.jaxws.sms.client.SMSResult
	 */
	@WebMethod(operationName = "SendSMSToIndia")
	@WebResult(name = "SMSResult", targetNamespace = "http://www.webserviceX.NET", partName = "Body")
	public SMSResult sendSMSToIndia(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "MobileNumber") String mobileNumber,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FromEmailAddress") String fromEmailAddress,
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Message") String message);

}
