package com.jlcindia.jaxws.sms.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SendSMSSoap", targetNamespace = "http://www.webserviceX.NET")
public interface SendSMSSoap {

	/**
	 * Send unlimited free SMS to India - Maximum message size is 120 characters<br>
	 * <br>
	 * <b>Usage:</b>If your mobile number is 098XXXXXXXX ,Please enter as
	 * 98XXXXXXXX<br>
	 * <b>Network Covered:</b> Airtel,Idea Cellular,Skycell ,RPG
	 * Cellular,Hutch,Celforce / Fascel,BPL Mobile,Escotel
	 * 
	 * @param mobileNumber
	 * @param fromEmailAddress
	 * @param message
	 * @return returns com.jlcindia.jaxws.sms.client.SMSResult
	 */
	@WebMethod(operationName = "SendSMSToIndia", action = "http://www.webserviceX.NET/SendSMSToIndia")
	@WebResult(name = "SendSMSToIndiaResult", targetNamespace = "http://www.webserviceX.NET")
	@RequestWrapper(localName = "SendSMSToIndia", targetNamespace = "http://www.webserviceX.NET", className = "com.jlcindia.jaxws.sms.client.SendSMSToIndia")
	@ResponseWrapper(localName = "SendSMSToIndiaResponse", targetNamespace = "http://www.webserviceX.NET", className = "com.jlcindia.jaxws.sms.client.SendSMSToIndiaResponse")
	public SMSResult sendSMSToIndia(
			@WebParam(name = "MobileNumber", targetNamespace = "http://www.webserviceX.NET") String mobileNumber,
			@WebParam(name = "FromEmailAddress", targetNamespace = "http://www.webserviceX.NET") String fromEmailAddress,
			@WebParam(name = "Message", targetNamespace = "http://www.webserviceX.NET") String message);

}
