package com.jlcindia.jaxws.sms.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * SendSMS service = new SendSMS();
 * SendSMSSoap portType = service.getSendSMSSoap();
 * portType.sendSMSToIndia(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "SendSMS", targetNamespace = "http://www.webserviceX.NET", wsdlLocation = "http://www.webservicex.net/SendSMS.asmx?WSDL")
public class SendSMS extends Service {

	private final static URL SENDSMS_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.jlcindia.jaxws.sms.client.SendSMS.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.jlcindia.jaxws.sms.client.SendSMS.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://www.webservicex.net/SendSMS.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/SendSMS.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SENDSMS_WSDL_LOCATION = url;
	}

	public SendSMS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public SendSMS() {
		super(SENDSMS_WSDL_LOCATION, new QName("http://www.webserviceX.NET",
				"SendSMS"));
	}

	/**
	 * 
	 * @return returns SendSMSSoap
	 */
	@WebEndpoint(name = "SendSMSSoap")
	public SendSMSSoap getSendSMSSoap() {
		return super.getPort(new QName("http://www.webserviceX.NET",
				"SendSMSSoap"), SendSMSSoap.class);
	}

	/**
	 * 
	 * @return returns SendSMSSoap
	 */
	@WebEndpoint(name = "SendSMSSoap12")
	public SendSMSSoap getSendSMSSoap12() {
		return super.getPort(new QName("http://www.webserviceX.NET",
				"SendSMSSoap12"), SendSMSSoap.class);
	}

	/**
	 * 
	 * @return returns SendSMSHttpGet
	 */
	@WebEndpoint(name = "SendSMSHttpGet")
	public SendSMSHttpGet getSendSMSHttpGet() {
		return super.getPort(new QName("http://www.webserviceX.NET",
				"SendSMSHttpGet"), SendSMSHttpGet.class);
	}

	/**
	 * 
	 * @return returns SendSMSHttpPost
	 */
	@WebEndpoint(name = "SendSMSHttpPost")
	public SendSMSHttpPost getSendSMSHttpPost() {
		return super.getPort(new QName("http://www.webserviceX.NET",
				"SendSMSHttpPost"), SendSMSHttpPost.class);
	}

}
