
package com.jlcindia.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 13:35:50 IST 2012
 * Generated source version: 2.2.12
 */

@XmlRootElement(name = "getMessageResponse", namespace = "http://cxf.jlcindia.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMessageResponse", namespace = "http://cxf.jlcindia.com/")

public class GetMessageResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

