
package com.jlcindia.cxf.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 13:35:50 IST 2012
 * Generated source version: 2.2.12
 */

@XmlRootElement(name = "getMessage", namespace = "http://cxf.jlcindia.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getMessage", namespace = "http://cxf.jlcindia.com/")

public class GetMessage {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

