package com.jlcindia.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 13:45:37 IST 2012
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://cxf.jlcindia.com/", name = "Hello")
@XmlSeeAlso({ObjectFactory.class})
public interface Hello {

    @ResponseWrapper(localName = "getMessageResponse", targetNamespace = "http://cxf.jlcindia.com/", className = "com.jlcindia.cxf.GetMessageResponse")
    @RequestWrapper(localName = "getMessage", targetNamespace = "http://cxf.jlcindia.com/", className = "com.jlcindia.cxf.GetMessage")
    @WebResult(name = "return", targetNamespace = "")
    @WebMethod(action = "urn:GetMessage")
    public java.lang.String getMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
