
package com.jlcindia.cxf;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 13:45:37 IST 2012
 * Generated source version: 2.2.12
 * 
 */

public final class Hello_HelloPort_Client {

    private static final QName SERVICE_NAME = new QName("http://cxf.jlcindia.com/", "HelloService");

    private Hello_HelloPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = HelloService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloService ss = new HelloService(wsdlURL, SERVICE_NAME);
        Hello port = ss.getHelloPort();  
        
        {
        System.out.println("Invoking getMessage...");
        java.lang.String _getMessage_arg0 = "_getMessage_arg02004588712";
        java.lang.String _getMessage__return = port.getMessage(_getMessage_arg0);
        System.out.println("getMessage.result=" + _getMessage__return);


        }

        System.exit(0);
    }

}
