
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.jlcindia.cxf;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Fri Jun 29 13:45:37 IST 2012
 * Generated source version: 2.2.12
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloService",
                      portName = "HelloPort",
                      targetNamespace = "http://cxf.jlcindia.com/",
                      wsdlLocation = "http://localhost:5555/HelloPort?wsdl",
                      endpointInterface = "com.jlcindia.cxf.Hello")
                      
public class HelloImpl implements Hello {

    private static final Logger LOG = Logger.getLogger(HelloImpl.class.getName());

    /* (non-Javadoc)
     * @see com.jlcindia.cxf.Hello#getMessage(java.lang.String  arg0 )*
     */
    public java.lang.String getMessage(java.lang.String arg0) { 
        LOG.info("Executing operation getMessage");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return1200367758";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
