package com.jlcindia.jaxws.sq.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * StockQuote service = new StockQuote();
 * StockQuoteSoap portType = service.getStockQuoteSoap();
 * portType.getQuote(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "StockQuote", targetNamespace = "http://www.webserviceX.NET/", wsdlLocation = "http://www.webservicex.net/stockquote.asmx?WSDL")
public class StockQuote extends Service {

	private final static URL STOCKQUOTE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.jlcindia.jaxws.sq.client.StockQuote.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.jlcindia.jaxws.sq.client.StockQuote.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://www.webservicex.net/stockquote.asmx?WSDL");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://www.webservicex.net/stockquote.asmx?WSDL', retrying as a local file");
			logger.warning(e.getMessage());
		}
		STOCKQUOTE_WSDL_LOCATION = url;
	}

	public StockQuote(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public StockQuote() {
		super(STOCKQUOTE_WSDL_LOCATION, new QName(
				"http://www.webserviceX.NET/", "StockQuote"));
	}

	/**
	 * 
	 * @return returns StockQuoteSoap
	 */
	@WebEndpoint(name = "StockQuoteSoap")
	public StockQuoteSoap getStockQuoteSoap() {
		return super.getPort(new QName("http://www.webserviceX.NET/",
				"StockQuoteSoap"), StockQuoteSoap.class);
	}

	/**
	 * 
	 * @return returns StockQuoteSoap
	 */
	@WebEndpoint(name = "StockQuoteSoap12")
	public StockQuoteSoap getStockQuoteSoap12() {
		return super.getPort(new QName("http://www.webserviceX.NET/",
				"StockQuoteSoap12"), StockQuoteSoap.class);
	}

	/**
	 * 
	 * @return returns StockQuoteHttpGet
	 */
	@WebEndpoint(name = "StockQuoteHttpGet")
	public StockQuoteHttpGet getStockQuoteHttpGet() {
		return super.getPort(new QName("http://www.webserviceX.NET/",
				"StockQuoteHttpGet"), StockQuoteHttpGet.class);
	}

	/**
	 * 
	 * @return returns StockQuoteHttpPost
	 */
	@WebEndpoint(name = "StockQuoteHttpPost")
	public StockQuoteHttpPost getStockQuoteHttpPost() {
		return super.getPort(new QName("http://www.webserviceX.NET/",
				"StockQuoteHttpPost"), StockQuoteHttpPost.class);
	}

}
