package com.jlcindia.jaxws.sq.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StockQuoteHttpGet", targetNamespace = "http://www.webserviceX.NET/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StockQuoteHttpGet {

	/**
	 * Get Stock quote for a company Symbol
	 * 
	 * @param symbol
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetQuote")
	@WebResult(name = "string", targetNamespace = "http://www.webserviceX.NET/", partName = "Body")
	public String getQuote(
			@WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "symbol") String symbol);

}
